Sys.Extended.UI.Localization["pt"] = {
    "AlwaysVisible_ElementRequired": "Sys.Extended.UI.AlwaysVisibleControlBehavior deve ter um elemento",
    "Animation_CannotNestSequence": "Sys.Extended.UI.Animation.SequenceAnimation não pode ser aninhado dentro de Sys.Extended.UI.Animation.ParallelAnimation",
    "Animation_ChildrenNotAllowed": "Sys.Extended.UI.Animation.createAnimation não pode adicionar animações filho para digitar \"{0}\" que não derive de Sys.Extended.UI.Animation.ParentAnimation",
    "Animation_InvalidBaseType": "Sys.Extended.UI.Animation.registerAnimation só pode registrar tipos que herdam de Sys.Extended.UI.Animation.Animation",
    "Animation_InvalidColor": "A cor deve ser uma representação sextavada de 7 caracteres (por exemplo, #246ACF), não \"{0}\"",
    "Animation_MissingAnimationName": "Sys.Extended.UI.Animation.createAnimation requer um objeto com uma propriedade AnimationName",
    "Animation_NoDynamicPropertyFound": "Sys.Extended.UI.Animation.createAnimation encontrou nenhuma propriedade correspondente a \"{0}\" ou \"{1}\"",
    "Animation_NoPropertyFound": "Sys.Extended.UI.Animation.createAnimation encontrou nenhuma propriedade correspondente a \"{0}\"",
    "Animation_TargetNotFound": "Sys.Extended.UI.Animation.Animation.set_animationTarget requer o ID de um Sys.UI.DomElement ou Sys.UI.Control. Nenhum elemento ou controle pode ser encontrado correspondente a \"{0}\"",
    "Animation_UknownAnimationName": "Sys.Extended.UI.Animation.createAnimation não encontrou uma Animação correspondente ao nome \"{0}\"",
    "Calendar_Today": "Hoje: {0}",
    "CascadingDropDown_MethodError": "[Metodo erro {0}]",
    "CascadingDropDown_MethodTimeout": "[Metodo tempo esgotado]",
    "CascadingDropDown_NoParentElement": "Falha ao encontrar o elemento pai \"{0}\"",
    "CollapsiblePanel_NoControlID": "Falha ao encontrar elemento \"{0}\"",
    "Common_DateTime_InvalidFormat": "Formato inválido",
    "Common_DateTime_InvalidTimeSpan": " \"{0}\" não é um formato de TimeSpan válido",
    "Common_InvalidBorderWidthUnit": "Um tipo de unidade de \"{0}\"\u0027 é inválido para parseBorderWidth",
    "Common_InvalidPaddingUnit": "Um tipo de unidade de \"{0}\" é inválido para parsePadding",
    "Common_UnitHasNoDigits": "Sem dígitos",
    "DynamicPopulate_WebServiceError": "Chamada do serviço da Web falhou: {0}",
    "DynamicPopulate_WebServiceTimeout": "Chamada de serviço da Web expirou",
    "ExtenderBase_CannotSetClientStateField": "clientStateField só pode ser definido antes da inicialização",
    "ExtenderBase_ControlNotRegisteredForCallbacks": "Este controle não foi registrado para callbacks",
    "ExtenderBase_InvalidClientStateType": "saveClientState deve retornar um valor do tipo String",
    "ExtenderBase_PageNotRegisteredForCallbacks": "Esta página não foi registrada para callbacks",
    "HTMLEditor_toolbar_button_FixedBackColor_title": "Cor de fundo",
    "HTMLEditor_toolbar_button_BackColorClear_title": "Limpar cor de fundo",
    "HTMLEditor_toolbar_button_Bold_title": "Negrito",
    "HTMLEditor_toolbar_button_BulletedList_title": "Lista com marcadores",
    "HTMLEditor_toolbar_button_Copy_title": "Copiar",
    "HTMLEditor_toolbar_button_Cut_title": "Recortar",
    "HTMLEditor_toolbar_button_DecreaseIndent_title": "Diminuir recuo",
    "HTMLEditor_toolbar_button_FontName_defaultValue": "padrão",
    "HTMLEditor_toolbar_button_FontSize_defaultValue": "padrão",
    "HTMLEditor_toolbar_button_DesignMode_title": "Modo de desenho",
    "HTMLEditor_toolbar_button_FontName_label": "Fonte",
    "HTMLEditor_toolbar_button_FixedForeColor_title": "Cor do primeiro plano",
    "HTMLEditor_toolbar_button_ForeColorClear_title": "Limpar cor do primeiro plano",
    "HTMLEditor_toolbar_button_HtmlMode_title": "Texto HTML",
    "HTMLEditor_toolbar_button_IncreaseIndent_title": "Aumentar recuo",
    "HTMLEditor_toolbar_button_InsertHR_title": "Inserir linha horizontal",
    "HTMLEditor_toolbar_button_InsertLink_title": "Inserir / Editar link de URL",
    "HTMLEditor_toolbar_button_InsertLink_message_EmptyURL": "URL não pode estar vazio",
    "HTMLEditor_toolbar_button_Italic_title": "Itálico",
    "HTMLEditor_toolbar_button_JustifyCenter_title": "Alinhar no Centro",
    "HTMLEditor_toolbar_button_JustifyFull_title": "Justificar",
    "HTMLEditor_toolbar_button_JustifyLeft_title": "Alinhar à Esquerda",
    "HTMLEditor_toolbar_button_JustifyRight_title": "Alinhar à Direita",
    "HTMLEditor_toolbar_button_Ltr_title": "Direção da esquerda para a direita",
    "HTMLEditor_toolbar_button_OnPasteFromMSWord": "Colar do MS Word ativado. Apenas agora: {0}",
    "HTMLEditor_toolbar_button_OnPastePlainText": "Colar texto simples ativada. Apenas agora: {0}",
    "HTMLEditor_toolbar_button_OrderedList_title": "Lista ordenada",
    "HTMLEditor_toolbar_button_Paragraph_title": "Criar Parágrafo",
    "HTMLEditor_toolbar_button_Paste_title": "Colar",
    "HTMLEditor_toolbar_button_PasteText_title": "Colar texto simples",
    "HTMLEditor_toolbar_button_PasteWord_title": "Colar do MS Word (com limpeza)",
    "HTMLEditor_toolbar_popup_LinkProperties_button_Cancel": "Cancelar",
    "HTMLEditor_toolbar_popup_LinkProperties_button_OK": "OK",
    "HTMLEditor_toolbar_popup_LinkProperties_field_URL": "URL",
    "HTMLEditor_toolbar_popup_LinkProperties_field_Target": "Alvo",
    "HTMLEditor_toolbar_popup_LinkProperties_field_Target_New": "Nova janela",
    "HTMLEditor_toolbar_popup_LinkProperties_field_Target_Current": "janela atual",
    "HTMLEditor_toolbar_popup_LinkProperties_field_Target_Parent": "Janela pai",
    "HTMLEditor_toolbar_popup_LinkProperties_field_Target_Top": "janela Top",
    "HTMLEditor_toolbar_button_PreviewMode_title": "Pré visualizar",
    "HTMLEditor_toolbar_button_Redo_title": "Refazer",
    "HTMLEditor_toolbar_button_RemoveAlignment_title": "Remover Alinhamento",
    "HTMLEditor_toolbar_button_RemoveLink_title": "Remover link",
    "HTMLEditor_toolbar_button_RemoveStyles_title": "Remover estilos",
    "HTMLEditor_toolbar_button_Rtl_title": "Direção da direita para a esquerda",
    "HTMLEditor_toolbar_button_FontSize_label": "Tamanho",
    "HTMLEditor_toolbar_button_StrikeThrough_title": "Traçado",
    "HTMLEditor_toolbar_button_SubScript_title": "Sub escrito",
    "HTMLEditor_toolbar_button_SuperScript_title": "Super escrito",
    "HTMLEditor_toolbar_button_Underline_title": "Sublinhado",
    "HTMLEditor_toolbar_button_Undo_title": "Desfazer",
    "HTMLEditor_toolbar_button_Use_verb": "Usar {0}",
    "ListSearch_DefaultPrompt": "Tipo para pesquisar",
    "PasswordStrength_DefaultStrengthDescriptions": "Não Existente, Muito Fraco, Fraco, Pobre, Quase OK, Aceitável, Médio, Bom, Forte, Excelente, Inquebrável!",
    "PasswordStrength_GetHelpRequirements": "Obter ajuda nos requisitos de senha",
    "PasswordStrength_InvalidStrengthDescriptions": "Número inválido de descrições de força do texto especificado",
    "PasswordStrength_InvalidStrengthDescriptionStyles": "As classes de estilo da descrição de força do texto devem corresponder ao número de descrições do texto.",
    "PasswordStrength_InvalidWeightingRatios": "Razões de ponderação de força devem ter 4 elementos",
    "PasswordStrength_RemainingCaracteres": "{0} mais letras",
    "PasswordStrength_RemainingLowerCase": "{0} mais letras minúsculas",
    "PasswordStrength_RemainingMixedCase": "Letras maiúsculas e minúsculas",
    "PasswordStrength_RemainingNumbers": "{0} mais números",
    "PasswordStrength_RemainingSymbols": "{0} símbolos",
    "PasswordStrength_RemainingUpperCase": "{0} mais letras maiúsculas",
    "PasswordStrength_Satisfied": "Nada mais necessário",
    "PasswordStrength_StrengthPrompt": "Força:",
    "PopupControl_NoDefaultProperty": "Nenhuma propriedade padrão suportada para o controle \"{0}\" do tipo \"{1}\"",
    "PopupExtender_NoParentElement": "Elemento pai \"{0}\" não pode ser encontrado",
    "Rating_CallbackError": "Ocorreu uma exceção não tratada:\\r\\n{0}",
    "ReorderList_DropWatcherBehavior_CallbackError": "Reordenar falhou, veja os detalhes abaixo. \\r\\n\\r\\n{0}",
    "ReorderList_DropWatcherBehavior_NoChild": "Não foi possível encontrar a lista filha com o id \"{0}\"",
    "ResizableControlBehavior_CannotChangeProperty": "Alterações para {0} não suportadas",
    "ResizableControlBehavior_InvalidHandler": "{0} manipulador não é uma função, nome da função ou texto da função",
    "RTE_BackgroundColor": "Cor de fundo",
    "RTE_BarColor": "Cor da barra",
    "RTE_Bold": "Negrito",
    "RTE_Border": "Borda",
    "RTE_BorderColor": "Cor da borda",
    "RTE_Cancelar": "Cancelar",
    "RTE_CellColor": "Cor da célula",
    "RTE_CellPadding": "Cell Padding",
    "RTE_CellSpacing": "Cell Spacing",
    "RTE_ClearFormatting": "Limpar Formatação",
    "RTE_Columns": "Colunas",
    "RTE_Copy": "Copiar",
    "RTE_Create": "Criar",
    "RTE_Cut": "Recortar",
    "RTE_Font": "Fonte",
    "RTE_FontColor": "Cor da fonte",
    "RTE_Heading": "Título",
    "RTE_Hyperlink": "Hyperlink",
    "RTE_Indent": "Indent",
    "RTE_InsertHorizontalRule": "Inserir linha horizontal",
    "RTE_InsertImage": "Inserir imagem",
    "RTE_InsertTable": "Inserir tabela",
    "RTE_Inserttexthere": "Inserir texto aqui",
    "RTE_Italic": "Itálico",
    "RTE_JustifyCenter": "Alinhar no Centro",
    "RTE_JustifyFull": "Justificar",
    "RTE_JustifyLeft": "Alinhar à Esquersa",
    "RTE_JustifyRight": "Alinhar à Direita",
    "RTE_LabelColor": "Cor do Rótulo",
    "RTE_Labels": "Rótulo",
    "RTE_Legend": "Legenda",
    "RTE_Normal": "Normal",
    "RTE_OK": "OK",
    "RTE_OrderedList": "Lista Ordenada",
    "RTE_Outdent": "Outdent",
    "RTE_Paragraph": "Parágrafo",
    "RTE_Paste": "Colar",
    "RTE_PreviewHTML": "Prever HTML",
    "RTE_Redo": "Refazer",
    "RTE_Rows": "Linhas",
    "RTE_Size": "Tamanho",
    "RTE_Underline": "Traço",
    "RTE_Undo": "Desfazer",
    "RTE_UnorderedList": "Lista não ordenada",
    "RTE_Values": "Valores",
    "RTE_ViewEditor": "Ver Editor",
    "RTE_ViewSource": "Ver Fonte",
    "RTE_ViewValues": "Ver valores",
    "Shared_BrowserSecurityPreventsPaste": "As configurações de segurança do seu navegador não permitem a execução automática das operações de colar. Por favor, use o atalho do teclado Ctrl + V em vez disso.",
    "Slider_NoSizeProvided": "Defina valores válidos para os atributos de altura e largura nas classes CSS dos slides",
    "Tabs_ActiveTabArgumentOutOfRange": "Argumento não é um membro da coleção de guias",
    "Tabs_OwnerExpected": "O proprietário deve ser definido antes de inicializar",
    "Tabs_PropertySetAfterInitialization": "{0} não pode ser alterado após a inicialização",
    "Tabs_PropertySetBeforeInitialization": "{0} não pode ser alterado antes da inicialização",
    "Tabs_UnknownTheme": "Tema {0} não pode ser convertido em uma classe CSS",
    "ValidatorCallout_DefaultErrorMessage": "Este controle é inválido",
    "MultiHandleSlider_CssHeightWidthRequired": "Você deve especificar uma largura e altura CSS para todos os estilos de identificador, bem como o trilho",
    "AsyncFileUpload_InternalErrorMessage": "O controle AsyncFileUpload encontrou um erro com o carregador nesta página. Atualize a página e tente novamente.",
    "AsyncFileUpload_UnhandledException": "Exceção não tratada",
    "AsyncFileUpload_ConfirmToSeeErrorPage": "Você deseja ver a página de resposta?",
    "AsyncFileUpload_ServerResponseError": "Erro de resposta do servidor",
    "AsyncFileUpload_UnknownServerError": "Erro do servidor desconhecido",
    "AsyncFileUpload_UploadingProblem": "Problema de carregamento do arquivo solicitado",
    "AjaxFileUpload_DropFiles": "Arraste arquivos aqui",
    "AjaxFileUpload_AllFilesUploaded": "Todos os arquivos carregados.",
    "AjaxFileUpload_SelectFile": "Selecionar arquivo(s)",
    "AjaxFileUpload_Remove": "Remover",
    "AjaxFileUpload_Upload": "Carregar",
    "AjaxFileUpload_Cancel": "Cancelar",
    "AjaxFileUpload_FileList": "Lista de arquivos carregados:",
    "AjaxFileUpload_SelectFileToUpload": "Selecione os arquivos a serem carregados",
    "AjaxFileUpload_Pending": "pendente",
    "AjaxFileUpload_FileInQueue": "{0} arquivo(s) na fila.",
    "AjaxFileUpload_UploadingFileInQueue": "Enviando {0} de {1} arquivo(s)",
    "AjaxFileUpload_UploadingHtml5File": "Fazendo o carregamento do arquivo: {0} do tamanho {1} bytes.",
    "AjaxFileUpload_UploadingInputFile": "Carregamento do arquivo: {0}.",
    "AjaxFileUpload_UploadError": "Ocorreu um erro durante o carregamento do arquivo",
    "AjaxFileUpload_DefaultError": "Erro de carregamento do arquivo",
    "AjaxFileUpload_UploadedPercentage": "Carregando {0}%",
    "AjaxFileUpload_Uploading": "Carregando",
    "AjaxFileUpload_Upload": "Carregado",
    "AjaxFileUpload_Cancelling": "Cancelando ...",
    "AjaxFileUpload_CancellingUpload": "Cancelando carregamento ...",
    "AjaxFileUpload_UploadCanceled": "Carregamento do arquivo cancelado",
    "AjaxFileUpload_Canceled": "cancelado",
    "AjaxFileUpload_error": "Erro",
    "AjaxFileUpload_MaxNumberOfFilesExceeded": "Número máximo de arquivos excedidos",
    "AjaxFileUpload_WrongFileType": "Você não pode carregar este arquivo \u0027{0}\u0027 para a lista. O arquivo com o tipo \u0027{1}\u0027 não é permitido",
    "AjaxFileUpload_TooLargeFile": "O tamanho do arquivo \u0027{0}\u0027 excede o limite {1} Kbytes."
}
